//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveInfo
    {
        public int Lid { get; set; }
        public string StuNum { get; set; }
        public string StuName { get; set; }
        public string Phone { get; set; }
        public string GNum { get; set; }
        public string CName { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Addresss { get; set; }
        public string Reason { get; set; }
        public string Principal { get; set; }
        public Nullable<int> Statu { get; set; }
    }
}
