//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qxb
    {
        public int Qid { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> GnId { get; set; }
    
        public virtual Gnb Gnb { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
