//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("Stu", "FK__Admins__RoleId__1273C1CD", "Roles", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Stu.Role), "Admins", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Stu.Admin), true)]
[assembly: EdmRelationshipAttribute("Stu", "FK__Class__Gid__1CF15040", "Grade", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Stu.Grade), "Class", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Stu.Class), true)]
[assembly: EdmRelationshipAttribute("Stu", "FK__Student__Cid__24927208", "Class", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Stu.Class), "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Stu.Student), true)]
[assembly: EdmRelationshipAttribute("Stu", "FK__Qxb__GnId__182C9B23", "Gnb", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Stu.Gnb), "Qxb", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Stu.Qxb), true)]
[assembly: EdmRelationshipAttribute("Stu", "FK__Student__Gid__239E4DCF", "Grade", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Stu.Grade), "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Stu.Student), true)]
[assembly: EdmRelationshipAttribute("Stu", "FK__Qxb__RoleId__173876EA", "Roles", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Stu.Role), "Qxb", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Stu.Qxb), true)]

#endregion

namespace Stu
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class StuEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“StuEntities”部分中的连接字符串初始化新 StuEntities 对象。
        /// </summary>
        public StuEntities() : base("name=StuEntities", "StuEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 StuEntities 对象。
        /// </summary>
        public StuEntities(string connectionString) : base(connectionString, "StuEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 StuEntities 对象。
        /// </summary>
        public StuEntities(EntityConnection connection) : base(connection, "StuEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Admin> Admins
        {
            get
            {
                if ((_Admins == null))
                {
                    _Admins = base.CreateObjectSet<Admin>("Admins");
                }
                return _Admins;
            }
        }
        private ObjectSet<Admin> _Admins;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Class> Classes
        {
            get
            {
                if ((_Classes == null))
                {
                    _Classes = base.CreateObjectSet<Class>("Classes");
                }
                return _Classes;
            }
        }
        private ObjectSet<Class> _Classes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Gnb> Gnbs
        {
            get
            {
                if ((_Gnbs == null))
                {
                    _Gnbs = base.CreateObjectSet<Gnb>("Gnbs");
                }
                return _Gnbs;
            }
        }
        private ObjectSet<Gnb> _Gnbs;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Grade> Grades
        {
            get
            {
                if ((_Grades == null))
                {
                    _Grades = base.CreateObjectSet<Grade>("Grades");
                }
                return _Grades;
            }
        }
        private ObjectSet<Grade> _Grades;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<LeaveInfo> LeaveInfoes
        {
            get
            {
                if ((_LeaveInfoes == null))
                {
                    _LeaveInfoes = base.CreateObjectSet<LeaveInfo>("LeaveInfoes");
                }
                return _LeaveInfoes;
            }
        }
        private ObjectSet<LeaveInfo> _LeaveInfoes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Qxb> Qxbs
        {
            get
            {
                if ((_Qxbs == null))
                {
                    _Qxbs = base.CreateObjectSet<Qxb>("Qxbs");
                }
                return _Qxbs;
            }
        }
        private ObjectSet<Qxb> _Qxbs;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Role> Roles
        {
            get
            {
                if ((_Roles == null))
                {
                    _Roles = base.CreateObjectSet<Role>("Roles");
                }
                return _Roles;
            }
        }
        private ObjectSet<Role> _Roles;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Student> Students
        {
            get
            {
                if ((_Students == null))
                {
                    _Students = base.CreateObjectSet<Student>("Students");
                }
                return _Students;
            }
        }
        private ObjectSet<Student> _Students;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Admins EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToAdmins(Admin admin)
        {
            base.AddObject("Admins", admin);
        }
    
        /// <summary>
        /// 用于向 Classes EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToClasses(Class @class)
        {
            base.AddObject("Classes", @class);
        }
    
        /// <summary>
        /// 用于向 Gnbs EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToGnbs(Gnb gnb)
        {
            base.AddObject("Gnbs", gnb);
        }
    
        /// <summary>
        /// 用于向 Grades EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToGrades(Grade grade)
        {
            base.AddObject("Grades", grade);
        }
    
        /// <summary>
        /// 用于向 LeaveInfoes EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToLeaveInfoes(LeaveInfo leaveInfo)
        {
            base.AddObject("LeaveInfoes", leaveInfo);
        }
    
        /// <summary>
        /// 用于向 Qxbs EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToQxbs(Qxb qxb)
        {
            base.AddObject("Qxbs", qxb);
        }
    
        /// <summary>
        /// 用于向 Roles EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToRoles(Role role)
        {
            base.AddObject("Roles", role);
        }
    
        /// <summary>
        /// 用于向 Students EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Stu", Name="Admin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Admin : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Admin 对象。
        /// </summary>
        /// <param name="aid">Aid 属性的初始值。</param>
        /// <param name="adminName">AdminName 属性的初始值。</param>
        /// <param name="adminPwd">AdminPwd 属性的初始值。</param>
        public static Admin CreateAdmin(global::System.Int32 aid, global::System.String adminName, global::System.String adminPwd)
        {
            Admin admin = new Admin();
            admin.Aid = aid;
            admin.AdminName = adminName;
            admin.AdminPwd = adminPwd;
            return admin;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Aid
        {
            get
            {
                return _Aid;
            }
            set
            {
                if (_Aid != value)
                {
                    OnAidChanging(value);
                    ReportPropertyChanging("Aid");
                    _Aid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Aid");
                    OnAidChanged();
                }
            }
        }
        private global::System.Int32 _Aid;
        partial void OnAidChanging(global::System.Int32 value);
        partial void OnAidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AdminName
        {
            get
            {
                return _AdminName;
            }
            set
            {
                OnAdminNameChanging(value);
                ReportPropertyChanging("AdminName");
                _AdminName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AdminName");
                OnAdminNameChanged();
            }
        }
        private global::System.String _AdminName;
        partial void OnAdminNameChanging(global::System.String value);
        partial void OnAdminNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AdminPwd
        {
            get
            {
                return _AdminPwd;
            }
            set
            {
                OnAdminPwdChanging(value);
                ReportPropertyChanging("AdminPwd");
                _AdminPwd = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AdminPwd");
                OnAdminPwdChanged();
            }
        }
        private global::System.String _AdminPwd;
        partial void OnAdminPwdChanging(global::System.String value);
        partial void OnAdminPwdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RoleId;
        partial void OnRoleIdChanging(Nullable<global::System.Int32> value);
        partial void OnRoleIdChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stu", "FK__Admins__RoleId__1273C1CD", "Roles")]
        public Role Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("Stu.FK__Admins__RoleId__1273C1CD", "Roles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("Stu.FK__Admins__RoleId__1273C1CD", "Roles").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Role> RoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("Stu.FK__Admins__RoleId__1273C1CD", "Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Role>("Stu.FK__Admins__RoleId__1273C1CD", "Roles", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Stu", Name="Class")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Class : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Class 对象。
        /// </summary>
        /// <param name="cid">Cid 属性的初始值。</param>
        public static Class CreateClass(global::System.Int32 cid)
        {
            Class @class = new Class();
            @class.Cid = cid;
            return @class;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cid
        {
            get
            {
                return _Cid;
            }
            set
            {
                if (_Cid != value)
                {
                    OnCidChanging(value);
                    ReportPropertyChanging("Cid");
                    _Cid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Cid");
                    OnCidChanged();
                }
            }
        }
        private global::System.Int32 _Cid;
        partial void OnCidChanging(global::System.Int32 value);
        partial void OnCidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CName
        {
            get
            {
                return _CName;
            }
            set
            {
                OnCNameChanging(value);
                ReportPropertyChanging("CName");
                _CName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CName");
                OnCNameChanged();
            }
        }
        private global::System.String _CName;
        partial void OnCNameChanging(global::System.String value);
        partial void OnCNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Gid
        {
            get
            {
                return _Gid;
            }
            set
            {
                OnGidChanging(value);
                ReportPropertyChanging("Gid");
                _Gid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Gid");
                OnGidChanged();
            }
        }
        private Nullable<global::System.Int32> _Gid;
        partial void OnGidChanging(Nullable<global::System.Int32> value);
        partial void OnGidChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stu", "FK__Class__Gid__1CF15040", "Grade")]
        public Grade Grade
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grade>("Stu.FK__Class__Gid__1CF15040", "Grade").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grade>("Stu.FK__Class__Gid__1CF15040", "Grade").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Grade> GradeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grade>("Stu.FK__Class__Gid__1CF15040", "Grade");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Grade>("Stu.FK__Class__Gid__1CF15040", "Grade", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stu", "FK__Student__Cid__24927208", "Student")]
        public EntityCollection<Student> Students
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student>("Stu.FK__Student__Cid__24927208", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student>("Stu.FK__Student__Cid__24927208", "Student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Stu", Name="Gnb")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Gnb : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Gnb 对象。
        /// </summary>
        /// <param name="gnId">GnId 属性的初始值。</param>
        /// <param name="gnName">GnName 属性的初始值。</param>
        public static Gnb CreateGnb(global::System.Int32 gnId, global::System.String gnName)
        {
            Gnb gnb = new Gnb();
            gnb.GnId = gnId;
            gnb.GnName = gnName;
            return gnb;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GnId
        {
            get
            {
                return _GnId;
            }
            set
            {
                if (_GnId != value)
                {
                    OnGnIdChanging(value);
                    ReportPropertyChanging("GnId");
                    _GnId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GnId");
                    OnGnIdChanged();
                }
            }
        }
        private global::System.Int32 _GnId;
        partial void OnGnIdChanging(global::System.Int32 value);
        partial void OnGnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GnName
        {
            get
            {
                return _GnName;
            }
            set
            {
                OnGnNameChanging(value);
                ReportPropertyChanging("GnName");
                _GnName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GnName");
                OnGnNameChanged();
            }
        }
        private global::System.String _GnName;
        partial void OnGnNameChanging(global::System.String value);
        partial void OnGnNameChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stu", "FK__Qxb__GnId__182C9B23", "Qxb")]
        public EntityCollection<Qxb> Qxbs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Qxb>("Stu.FK__Qxb__GnId__182C9B23", "Qxb");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Qxb>("Stu.FK__Qxb__GnId__182C9B23", "Qxb", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Stu", Name="Grade")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Grade : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Grade 对象。
        /// </summary>
        /// <param name="gid">Gid 属性的初始值。</param>
        public static Grade CreateGrade(global::System.Int32 gid)
        {
            Grade grade = new Grade();
            grade.Gid = gid;
            return grade;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Gid
        {
            get
            {
                return _Gid;
            }
            set
            {
                if (_Gid != value)
                {
                    OnGidChanging(value);
                    ReportPropertyChanging("Gid");
                    _Gid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Gid");
                    OnGidChanged();
                }
            }
        }
        private global::System.Int32 _Gid;
        partial void OnGidChanging(global::System.Int32 value);
        partial void OnGidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GNum
        {
            get
            {
                return _GNum;
            }
            set
            {
                OnGNumChanging(value);
                ReportPropertyChanging("GNum");
                _GNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GNum");
                OnGNumChanged();
            }
        }
        private global::System.String _GNum;
        partial void OnGNumChanging(global::System.String value);
        partial void OnGNumChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stu", "FK__Class__Gid__1CF15040", "Class")]
        public EntityCollection<Class> Classes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Class>("Stu.FK__Class__Gid__1CF15040", "Class");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Class>("Stu.FK__Class__Gid__1CF15040", "Class", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stu", "FK__Student__Gid__239E4DCF", "Student")]
        public EntityCollection<Student> Students
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student>("Stu.FK__Student__Gid__239E4DCF", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student>("Stu.FK__Student__Gid__239E4DCF", "Student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Stu", Name="LeaveInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LeaveInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 LeaveInfo 对象。
        /// </summary>
        /// <param name="lid">Lid 属性的初始值。</param>
        /// <param name="stuNum">StuNum 属性的初始值。</param>
        /// <param name="stuName">StuName 属性的初始值。</param>
        /// <param name="phone">Phone 属性的初始值。</param>
        /// <param name="gNum">GNum 属性的初始值。</param>
        /// <param name="cName">CName 属性的初始值。</param>
        /// <param name="beginDate">BeginDate 属性的初始值。</param>
        /// <param name="endDate">EndDate 属性的初始值。</param>
        /// <param name="addresss">Addresss 属性的初始值。</param>
        /// <param name="reason">Reason 属性的初始值。</param>
        /// <param name="principal">Principal 属性的初始值。</param>
        public static LeaveInfo CreateLeaveInfo(global::System.Int32 lid, global::System.String stuNum, global::System.String stuName, global::System.String phone, global::System.String gNum, global::System.String cName, global::System.DateTime beginDate, global::System.DateTime endDate, global::System.String addresss, global::System.String reason, global::System.String principal)
        {
            LeaveInfo leaveInfo = new LeaveInfo();
            leaveInfo.Lid = lid;
            leaveInfo.StuNum = stuNum;
            leaveInfo.StuName = stuName;
            leaveInfo.Phone = phone;
            leaveInfo.GNum = gNum;
            leaveInfo.CName = cName;
            leaveInfo.BeginDate = beginDate;
            leaveInfo.EndDate = endDate;
            leaveInfo.Addresss = addresss;
            leaveInfo.Reason = reason;
            leaveInfo.Principal = principal;
            return leaveInfo;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Lid
        {
            get
            {
                return _Lid;
            }
            set
            {
                if (_Lid != value)
                {
                    OnLidChanging(value);
                    ReportPropertyChanging("Lid");
                    _Lid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Lid");
                    OnLidChanged();
                }
            }
        }
        private global::System.Int32 _Lid;
        partial void OnLidChanging(global::System.Int32 value);
        partial void OnLidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StuNum
        {
            get
            {
                return _StuNum;
            }
            set
            {
                OnStuNumChanging(value);
                ReportPropertyChanging("StuNum");
                _StuNum = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StuNum");
                OnStuNumChanged();
            }
        }
        private global::System.String _StuNum;
        partial void OnStuNumChanging(global::System.String value);
        partial void OnStuNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StuName
        {
            get
            {
                return _StuName;
            }
            set
            {
                OnStuNameChanging(value);
                ReportPropertyChanging("StuName");
                _StuName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StuName");
                OnStuNameChanged();
            }
        }
        private global::System.String _StuName;
        partial void OnStuNameChanging(global::System.String value);
        partial void OnStuNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GNum
        {
            get
            {
                return _GNum;
            }
            set
            {
                OnGNumChanging(value);
                ReportPropertyChanging("GNum");
                _GNum = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GNum");
                OnGNumChanged();
            }
        }
        private global::System.String _GNum;
        partial void OnGNumChanging(global::System.String value);
        partial void OnGNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CName
        {
            get
            {
                return _CName;
            }
            set
            {
                OnCNameChanging(value);
                ReportPropertyChanging("CName");
                _CName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CName");
                OnCNameChanged();
            }
        }
        private global::System.String _CName;
        partial void OnCNameChanging(global::System.String value);
        partial void OnCNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BeginDate
        {
            get
            {
                return _BeginDate;
            }
            set
            {
                OnBeginDateChanging(value);
                ReportPropertyChanging("BeginDate");
                _BeginDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BeginDate");
                OnBeginDateChanged();
            }
        }
        private global::System.DateTime _BeginDate;
        partial void OnBeginDateChanging(global::System.DateTime value);
        partial void OnBeginDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Addresss
        {
            get
            {
                return _Addresss;
            }
            set
            {
                OnAddresssChanging(value);
                ReportPropertyChanging("Addresss");
                _Addresss = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Addresss");
                OnAddresssChanged();
            }
        }
        private global::System.String _Addresss;
        partial void OnAddresssChanging(global::System.String value);
        partial void OnAddresssChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Reason
        {
            get
            {
                return _Reason;
            }
            set
            {
                OnReasonChanging(value);
                ReportPropertyChanging("Reason");
                _Reason = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Reason");
                OnReasonChanged();
            }
        }
        private global::System.String _Reason;
        partial void OnReasonChanging(global::System.String value);
        partial void OnReasonChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Principal
        {
            get
            {
                return _Principal;
            }
            set
            {
                OnPrincipalChanging(value);
                ReportPropertyChanging("Principal");
                _Principal = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Principal");
                OnPrincipalChanged();
            }
        }
        private global::System.String _Principal;
        partial void OnPrincipalChanging(global::System.String value);
        partial void OnPrincipalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Statu
        {
            get
            {
                return _Statu;
            }
            set
            {
                OnStatuChanging(value);
                ReportPropertyChanging("Statu");
                _Statu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Statu");
                OnStatuChanged();
            }
        }
        private Nullable<global::System.Int32> _Statu;
        partial void OnStatuChanging(Nullable<global::System.Int32> value);
        partial void OnStatuChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Stu", Name="Qxb")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Qxb : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Qxb 对象。
        /// </summary>
        /// <param name="qid">Qid 属性的初始值。</param>
        public static Qxb CreateQxb(global::System.Int32 qid)
        {
            Qxb qxb = new Qxb();
            qxb.Qid = qid;
            return qxb;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Qid
        {
            get
            {
                return _Qid;
            }
            set
            {
                if (_Qid != value)
                {
                    OnQidChanging(value);
                    ReportPropertyChanging("Qid");
                    _Qid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Qid");
                    OnQidChanged();
                }
            }
        }
        private global::System.Int32 _Qid;
        partial void OnQidChanging(global::System.Int32 value);
        partial void OnQidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RoleId;
        partial void OnRoleIdChanging(Nullable<global::System.Int32> value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GnId
        {
            get
            {
                return _GnId;
            }
            set
            {
                OnGnIdChanging(value);
                ReportPropertyChanging("GnId");
                _GnId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GnId");
                OnGnIdChanged();
            }
        }
        private Nullable<global::System.Int32> _GnId;
        partial void OnGnIdChanging(Nullable<global::System.Int32> value);
        partial void OnGnIdChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stu", "FK__Qxb__GnId__182C9B23", "Gnb")]
        public Gnb Gnb
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gnb>("Stu.FK__Qxb__GnId__182C9B23", "Gnb").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gnb>("Stu.FK__Qxb__GnId__182C9B23", "Gnb").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Gnb> GnbReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Gnb>("Stu.FK__Qxb__GnId__182C9B23", "Gnb");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Gnb>("Stu.FK__Qxb__GnId__182C9B23", "Gnb", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stu", "FK__Qxb__RoleId__173876EA", "Roles")]
        public Role Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("Stu.FK__Qxb__RoleId__173876EA", "Roles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("Stu.FK__Qxb__RoleId__173876EA", "Roles").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Role> RoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("Stu.FK__Qxb__RoleId__173876EA", "Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Role>("Stu.FK__Qxb__RoleId__173876EA", "Roles", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Stu", Name="Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Role : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Role 对象。
        /// </summary>
        /// <param name="roleId">RoleId 属性的初始值。</param>
        /// <param name="roleName">RoleName 属性的初始值。</param>
        public static Role CreateRole(global::System.Int32 roleId, global::System.String roleName)
        {
            Role role = new Role();
            role.RoleId = roleId;
            role.RoleName = roleName;
            return role;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                if (_RoleId != value)
                {
                    OnRoleIdChanging(value);
                    ReportPropertyChanging("RoleId");
                    _RoleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleId");
                    OnRoleIdChanged();
                }
            }
        }
        private global::System.Int32 _RoleId;
        partial void OnRoleIdChanging(global::System.Int32 value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                OnRoleNameChanging(value);
                ReportPropertyChanging("RoleName");
                _RoleName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RoleName");
                OnRoleNameChanged();
            }
        }
        private global::System.String _RoleName;
        partial void OnRoleNameChanging(global::System.String value);
        partial void OnRoleNameChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stu", "FK__Admins__RoleId__1273C1CD", "Admins")]
        public EntityCollection<Admin> Admins
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Admin>("Stu.FK__Admins__RoleId__1273C1CD", "Admins");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Admin>("Stu.FK__Admins__RoleId__1273C1CD", "Admins", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stu", "FK__Qxb__RoleId__173876EA", "Qxb")]
        public EntityCollection<Qxb> Qxbs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Qxb>("Stu.FK__Qxb__RoleId__173876EA", "Qxb");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Qxb>("Stu.FK__Qxb__RoleId__173876EA", "Qxb", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Stu", Name="Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Student 对象。
        /// </summary>
        /// <param name="stuId">StuId 属性的初始值。</param>
        /// <param name="stuNum">StuNum 属性的初始值。</param>
        /// <param name="stuName">StuName 属性的初始值。</param>
        /// <param name="phone">Phone 属性的初始值。</param>
        public static Student CreateStudent(global::System.Int32 stuId, global::System.String stuNum, global::System.String stuName, global::System.String phone)
        {
            Student student = new Student();
            student.StuId = stuId;
            student.StuNum = stuNum;
            student.StuName = stuName;
            student.Phone = phone;
            return student;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StuId
        {
            get
            {
                return _StuId;
            }
            set
            {
                if (_StuId != value)
                {
                    OnStuIdChanging(value);
                    ReportPropertyChanging("StuId");
                    _StuId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StuId");
                    OnStuIdChanged();
                }
            }
        }
        private global::System.Int32 _StuId;
        partial void OnStuIdChanging(global::System.Int32 value);
        partial void OnStuIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StuNum
        {
            get
            {
                return _StuNum;
            }
            set
            {
                OnStuNumChanging(value);
                ReportPropertyChanging("StuNum");
                _StuNum = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StuNum");
                OnStuNumChanged();
            }
        }
        private global::System.String _StuNum;
        partial void OnStuNumChanging(global::System.String value);
        partial void OnStuNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StuName
        {
            get
            {
                return _StuName;
            }
            set
            {
                OnStuNameChanging(value);
                ReportPropertyChanging("StuName");
                _StuName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StuName");
                OnStuNameChanged();
            }
        }
        private global::System.String _StuName;
        partial void OnStuNameChanging(global::System.String value);
        partial void OnStuNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Gid
        {
            get
            {
                return _Gid;
            }
            set
            {
                OnGidChanging(value);
                ReportPropertyChanging("Gid");
                _Gid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Gid");
                OnGidChanged();
            }
        }
        private Nullable<global::System.Int32> _Gid;
        partial void OnGidChanging(Nullable<global::System.Int32> value);
        partial void OnGidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cid
        {
            get
            {
                return _Cid;
            }
            set
            {
                OnCidChanging(value);
                ReportPropertyChanging("Cid");
                _Cid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cid");
                OnCidChanged();
            }
        }
        private Nullable<global::System.Int32> _Cid;
        partial void OnCidChanging(Nullable<global::System.Int32> value);
        partial void OnCidChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stu", "FK__Student__Cid__24927208", "Class")]
        public Class Class
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Class>("Stu.FK__Student__Cid__24927208", "Class").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Class>("Stu.FK__Student__Cid__24927208", "Class").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Class> ClassReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Class>("Stu.FK__Student__Cid__24927208", "Class");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Class>("Stu.FK__Student__Cid__24927208", "Class", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Stu", "FK__Student__Gid__239E4DCF", "Grade")]
        public Grade Grade
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grade>("Stu.FK__Student__Gid__239E4DCF", "Grade").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grade>("Stu.FK__Student__Gid__239E4DCF", "Grade").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Grade> GradeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grade>("Stu.FK__Student__Gid__239E4DCF", "Grade");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Grade>("Stu.FK__Student__Gid__239E4DCF", "Grade", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
