//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class studentLeaveSystemEntities : DbContext
    {
        public studentLeaveSystemEntities()
            : base("name=studentLeaveSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Gnb> Gnb { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<LeaveInfo> LeaveInfo { get; set; }
        public virtual DbSet<Qxb> Qxb { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Student> Student { get; set; }
    }
}
